### ISSUE TITLE
Incompatibility with miniwdl>=1.12.1

### ISSUE THREAD

**Issue by giuliovn** [biowdl/wdl-aid#19]
After https://github.com/chanzuckerberg/miniwdl/releases/tag/v1.12.1, that update some python tooling around `miniwdl`, the installation of `wdl-aid` because of some incompatibility.
`miniwdl` entry in `requirements.txt` is `miniwdl>=1.0`, meaning it willl bring the latest, incompatible, version of `miniwdl`.

## How to reproduce
```bash
giulio@giulio:/tmp/w$ python -m venv v
giulio@giulio:/tmp/w$ source v/bin/activate
(v) giulio@giulio:/tmp/w$ python -V
Python 3.12.3
(v) giulio@giulio:/tmp/w$ python -m pip install wdl-aid
... installation logs omitted ...
(v) giulio@giulio:/tmp/w$ wdl-aid --version
Traceback (most recent call last):
  File "/tmp/w/v/bin/wdl-aid", line 5, in <module>
    from wdl_aid.wdl_aid import main
  File "/tmp/w/v/lib/python3.12/site-packages/wdl_aid/__init__.py", line 21, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(v) giulio@giulio:/tmp/w$ miniwdl --version
miniwdl v1.12.1
Traceback (most recent call last):
  File "/tmp/w/v/bin/miniwdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/w/v/lib/python3.12/site-packages/WDL/CLI.py", line 67, in main
    args = parser.parse_args(args if args is not None else sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giulio/.rye/py/cpython@3.12.3/lib/python3.12/argparse.py", line 1896, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giulio/.rye/py/cpython@3.12.3/lib/python3.12/argparse.py", line 1929, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giulio/.rye/py/cpython@3.12.3/lib/python3.12/argparse.py", line 2150, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giulio/.rye/py/cpython@3.12.3/lib/python3.12/argparse.py", line 2090, in consume_optional
    take_action(action, args, option_string)
  File "/home/giulio/.rye/py/cpython@3.12.3/lib/python3.12/argparse.py", line 2005, in take_action
    action(self, namespace, argument_values, option_string)
  File "/tmp/w/v/lib/python3.12/site-packages/WDL/CLI.py", line 149, in __call__
    import pkg_resources  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by DavyCats** [comment]
Thanks for reporting to issue. This doesn't really seem to be issue with wdl-aid or miniwdl, or the interplay between them. Rather, this seems to be an issue where some installations of python are missing the setuptools package. As far as I'm aware this package usually gets installed whenever pip does, but it seems it doesn't get taken along into new virtual environments. Installing setuptools seems to resolve the issue:

```bash
$ podman run -it docker.io/ubuntu:24.04 bash
root@1aca336cc911:/# apt update && apt install python3.12 python3-pip python3-virtualenv
[...]
done.
root@1aca336cc911:/# virtualenv v
created virtual environment CPython3.12.3.final.0-64 in 526ms
  creator CPython3Posix(dest=/v, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==24.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
root@1aca336cc911:/# . v/bin/activate
(v) root@1aca336cc911:/# pip --version
pip 24.0 from /v/lib/python3.12/site-packages/pip (python 3.12)
(v) root@1aca336cc911:/# pip install wdl-aid
[...]
Successfully installed MarkupSafe-2.1.5 PyYAML-6.0.2 argcomplete-3.5.0 bullet-2.2.0 certifi-2024.8.30 charset-normalizer-3.3.2 coloredlogs-15.0.1 docker-7.1.0 humanfriendly-10.0 idna-3.8 importlib-metadata-8.4.0 jinja2-3.1.4 lark-1.2.2 miniwdl-1.12.1 psutil-6.0.0 pygtail-0.14.0 python-json-logger-2.0.7 regex-2024.7.24 requests-2.32.3 urllib3-2.2.2 wdl-aid-1.0.0 xdg-6.0.0 zipp-3.20.1
(v) root@1aca336cc911:/# wdl-aid --version
Traceback (most recent call last):
  File "/v/bin/wdl-aid", line 5, in <module>
    from wdl_aid.wdl_aid import main
  File "/v/lib/python3.12/site-packages/wdl_aid/__init__.py", line 21, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
(v) root@1aca336cc911:/# pip install setuptools
Collecting setuptools
  Downloading setuptools-74.1.2-py3-none-any.whl.metadata (6.7 kB)
Downloading setuptools-74.1.2-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 29.6 MB/s eta 0:00:00
Installing collected packages: setuptools
Successfully installed setuptools-74.1.2
(v) root@1aca336cc911:/# wdl-aid --version
WDL-AID 1.0.0
(v) root@1aca336cc911:/# miniwdl --version
miniwdl v1.12.1
```

**Comment by giuliovn** [comment]
hi Davy, thank you for the answer!
I agree that installing `setuptools` will solve the issue, but this still means that `wdl-aid` installation is broken and the package is not self-contained and doesn't bring all its dependencies.
I think adding `setuptools` to `setup.py` and `requirements.txt` (for documentation) is a better solution. I tested it locally and seems to work.
I can issue a PR later, if you prefer.

**Comment by DavyCats** [comment]
You're right. WDL-AID actually uses this pkg_resources to retrieve the jinja2 template, so this should just be an explicit requirement. I've made a new release (v1.0.1) which has setuptools listed as a dependency.

**Comment by giuliovn** [comment]
Great, thank you!

**Comment by edmorley** [comment]
> As far as I'm aware this package usually gets installed whenever pip does

Note this changed with Python 3.12:
https://docs.python.org/3/whatsnew/3.12.html#ensurepip

Specifically:

> Remove the bundled setuptools wheel from [ensurepip](https://docs.python.org/3/library/ensurepip.html#module-ensurepip), and stop installing setuptools in environments created by [venv](https://docs.python.org/3/library/venv.html#module-venv).
